// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqylaHS5YqAUKFEqEDjRa7ZDyYS3l5A7w',
    appId: '1:400944230848:web:78951c20c779c4a4949825',
    messagingSenderId: '400944230848',
    projectId: 'be-safe-bd',
    authDomain: 'be-safe-bd.firebaseapp.com',
    storageBucket: 'be-safe-bd.appspot.com',
    measurementId: 'G-2CP6B9KDY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj0LtS4pb_YUW4CCZCdw8xIg-SVAxO7Nw',
    appId: '1:400944230848:android:c03a28ef5044178d949825',
    messagingSenderId: '400944230848',
    projectId: 'be-safe-bd',
    storageBucket: 'be-safe-bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEweY9FieUORn3FU56dU2OThbRaTt57v8',
    appId: '1:400944230848:ios:6a7164506098afda949825',
    messagingSenderId: '400944230848',
    projectId: 'be-safe-bd',
    storageBucket: 'be-safe-bd.appspot.com',
    iosBundleId: 'com.example.beSafe',
  );
}
